version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
  build:
    commands:
      - java -version
      - mvn clean install
      - cp ozru-user-service/target/ozru-user-service-0.0.1-SNAPSHOT.jar dist
artifacts:
  files:
    - './**/*'
  base-directory: 'dist'
