version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
  build:
    commands:
      - java -version
      - mvn clean install
artifacts:
  base-directory: ozru-user-service/target
  files:
    - ozru-user-service-0.0.1-SNAPSHOT.jar
